In [1]:
import pandas as pd

In [2]:
#read in data from 2 data sources
shot_types = pd.read_csv('nba_shot_types.csv')
season_data = pd.read_csv('Seasons_Stats.csv')

In [32]:
season_data.columns

Index(['Unnamed: 0', 'Year', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP',
       'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%',
       'BLK%', 'TOV%', 'USG%', 'blanl', 'OWS', 'DWS', 'WS', 'WS/48', 'blank2',
       'OBPM', 'DBPM', 'BPM', 'VORP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%',
       '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB',
       'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [3]:
#view columns
season_data.columns
shot_types.columns

Index(['YEAR', 'PLAYER', 'TEAM', 'AGE', 'GP', 'W', 'L', 'MIN', 'PCT_FGA_2PT',
       'PCT_FGA_3PT', 'PCT_PTS_2PT', 'PCT_PTS_MR', 'PCT_PTS_3PT',
       'PCT_PTS_FSTBRK', 'PCT_PTS_FT', 'PCT_PTS_OFF_TOS', 'PCT_PTS_INTHEPT',
       'PCT_2PTGFM_ASSTD', 'PCT_2PTGFM_UNASSTD', 'PCT_3PTGFM_ASSTD',
       'PCT_3PTGFM_UNASSTD', 'PCT_FGM_ASSTD', 'PCT_FGM_UNASSTD'],
      dtype='object')

In [10]:
#groupby so that each player only has 1 row/ season
#name, year = unique identifier shared between both tables
shot_types_grouped = shot_types.groupby(['PLAYER', 'YEAR']).mean()

In [31]:
shot_types_grouped.head()

                   AGE  GP   W   L   MIN  PCT_FGA_2PT  PCT_FGA_3PT  \
PLAYER       YEAR
AJ Hammons   2017   24  22   4  18   7.4         76.2         23.8
AJ Price     2014   27  28  15  13   3.5         52.2         47.8
             2015   28  26  11  15  12.4         58.4         41.6
Aaron Brooks 2014   29  72  42  30  21.6         57.3         42.7
             2015   30  82  50  32  23.0         61.7         38.3

                   PCT_PTS_2PT  PCT_PTS_MR  PCT_PTS_3PT  PCT_PTS_FSTBRK  \
PLAYER       YEAR
AJ Hammons   2017         50.0        29.2         31.3             4.2
AJ Price     2014         59.1        40.9         40.9            11.4
             2015         54.1        31.6         33.8             3.8
Aaron Brooks 2014         42.5         9.9         44.7            10.9
             2015         46.8        10.5         38.1             9.5

                   PCT_PTS_FT  PCT_PTS_OFF_TOS  PCT_PTS_INTHEPT  \
PLAYER       YEAR
AJ Hammons   2017        18.8             12.5             20.8
AJ Price     2014         0.0             11.4             18.2
             2015        12.0             21.1             22.6
Aaron Brooks 2014        12.9             13.8             32.6
             2015        15.2              7.1             36.3

                   PCT_2PTGFM_ASSTD  PCT_2PTGFM_UNASSTD  PCT_3PTGFM_ASSTD  \
PLAYER       YEAR
AJ Hammons   2017              91.7                 8.3             100.0
AJ Price     2014              23.1                76.9              83.3
             2015              11.1                88.9              66.7
Aaron Brooks 2014              13.9                86.1              69.8
             2015              12.6                87.4              61.2

                   PCT_3PTGFM_UNASSTD  PCT_FGM_ASSTD  PCT_FGM_UNASSTD
PLAYER       YEAR
AJ Hammons   2017                 0.0           94.1              5.9
AJ Price     2014                16.7           42.1             57.9
             2015                33.3           27.5             72.5
Aaron Brooks 2014                30.2           36.9             63.1
             2015                38.8           29.7             70.3

In [14]:
#this table should not need to be formated, but just in case. 
season_data_grouped = season_data.groupby(['Player', 'Year']).mean()

In [16]:
season_data_grouped.head()

                   Unnamed: 0   Age     G    GS      MP   PER    TS%   3PAr  \
Player     Year
A.C. Green 1986.0      8035.0  22.0  82.0   1.0  1542.0  11.8  0.564  0.015
           1987.0      8420.0  23.0  79.0  72.0  2240.0  15.7  0.599  0.009
           1988.0      8807.0  24.0  82.0  64.0  2636.0  14.5  0.581  0.003
           1989.0      9242.0  25.0  82.0  82.0  2510.0  17.8  0.594  0.022
           1990.0      9688.0  26.0  82.0  82.0  2709.0  14.7  0.548  0.057

                     FTr  ORB%  ...    FT%    ORB    DRB    TRB    AST   STL  \
Player     Year                 ...
A.C. Green 1986.0  0.430  12.4  ...  0.611  160.0  221.0  381.0   54.0  49.0
           1987.0  0.480  11.2  ...  0.780  210.0  405.0  615.0   84.0  70.0
           1988.0  0.592  11.1  ...  0.773  245.0  465.0  710.0   93.0  87.0
           1989.0  0.474  12.3  ...  0.786  258.0  481.0  739.0  103.0  94.0
           1990.0  0.459  11.5  ...  0.751  262.0  450.0  712.0   90.0  66.0

                    BLK    TOV     PF     PTS
Player     Year
A.C. Green 1986.0  49.0   99.0  229.0   521.0
           1987.0  80.0  102.0  171.0   852.0
           1988.0  45.0  120.0  204.0   937.0
           1989.0  55.0  119.0  172.0  1088.0
           1990.0  50.0  116.0  207.0  1061.0

[5 rows x 49 columns]

In [ ]:
#write both new data files to_csv, so they can be uploaded to pg admin
season_data_grouped.to_csv('season_data_grouped.csv')

In [ ]:
shot_types_grouped.to_csv('shot_types_grouped.csv')